version: "3"

services:
  spark-master:
    image: apache/spark:v3.1.3
    container_name: spark-master
    hostname: spark-master
    restart: always
    ports:
      # - "9870:9870"
      - "8080:8080"
    environment:
      - SPARK_MODE=master
      
    # volumes:
    networks:
      - bridge

  spark-worker01:
    image: apache/spark:v3.1.3
    container_name: spark-worker01
    hostname: spark-worker01
    restart: always
    ports:
      - "8081:8081"
    depends_on:
      - spark_master
    environment:
      - SPARK_MODE=slave

    # volumes:
    networks:
      - bridge

  spark-worker02:
    image: apache/spark:v3.1.3
    container_name: spark-worker02
    hostname: spark-worker02
    restart: always
    ports:
      - "8082:8081"
    depends_on:
      - spark_master
    environment:
      - SPARK_MODE=slave

    # volumes:
    networks:
      - bridge
  
  zeppeline:
    image: apache/zeppelin:0.8.2
    container_name: zeppelin
    hostname: zeppelin
    restart: always
    depends_on:
      - spark-master
      - spark-worker01
      - spark-worker02
    ports:
      - "8888:8080"
    environment:
      - SPARK_MODE=zeppelin

    volumes:
      - ./workspace:/workspace
    networks:
      - bridge

volumes:
  spark:
    driver: local

networks:
  bridge: